# Generated by Django 6.0.5 on 2026-05-19 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("categoria", models.CharField(max_length=100)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("Baixa", "Baixa"),
                            ("Média", "Média"),
                            ("Alta", "Alta"),
                            ("Crítica", "Crítica"),
                        ],
                        default="Média",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aberto", "Aberto"),
                            ("Em análise", "Em análise"),
                            (
                                "Aguardando resposta da solicitante",
                                "Aguardando resposta da solicitante",
                            ),
                            (
                                "Aguardando atendimento presencial",
                                "Aguardando atendimento presencial",
                            ),
                            ("Resolvido", "Resolvido"),
                            ("Finalizado", "Finalizado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Aberto",
                        max_length=50,
                    ),
                ),
                (
                    "tipo_atendimento",
                    models.CharField(
                        blank=True,
                        choices=[("Remoto", "Remoto"), ("Presencial", "Presencial")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                ("data_fechamento", models.DateTimeField(blank=True, null=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.sector",
                    ),
                ),
                (
                    "tecnico_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_atendidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=255)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tickets.ticket",
                    ),
                ),
            ],
        ),
    ]
